### ISSUE TITLE
[stdlib]todo list

### ISSUE THREAD

**Issue by tiangong3624749** [starcoinorg/starcoin-framework#10]
TODO:

- [x] PackageTxnManager：fire event in fun package_txn_epilogue

- [ ] Dao：multi votes & propose multi proposals & add a token manage cap in Token module

- [ ] Offer：should support multi Offer

- [x] TokenLockPool：how to init other token's pool

- [x] UpgradeModuleDaoProposal：should check duplicate cap?

- [x] ModifyDaoConfigProposal：assert cap.account_address == token_issuer

- [ ] Authenticator：添加2个常量，用于区分是否多签

- [x] Version：定义一个error code

- [ ] 其他：spec的todo

Fix me：

- [x] SortedLinkedList：the pointers at prev & next

- [x] Config：ModifyConfigCapability的events should put into Config resource

- [x] PackageTxnManager：submit_upgrade_plan_with_cap有一个assert被注释掉了

- [ ] 其他：spec的fix me
